#!/bin/bash

day=$(date +'%d')

cuser="${SUDO_USER:-$USER}"
circle=true
if [ -d /home/"$cuser"/.local/share/icons/Numix-Circle/ ]; then
    dircircle=/home/"$cuser"/.local/share/icons/Numix-Circle/
elif [ -d /home/"$cuser"/.icons/Numix-Circle/ ]; then
    dircircle=/home/"$cuser"/.icons/Numix-Circle/
elif [ -d /usr/share/icons/Numix-Circle/ ]; then
     dircircle=/usr/share/icons/Numix-Circle/
else
    circle=false
fi

square=true
if [ -d /home/"$cuser"/.local/share/icons/Numix-Square/ ]; then
    dirsquare=/home/"$cuser"/.local/share/icons/Numix-Square/
elif [ -d /home/"$cuser"/.icons/Numix-Square/ ]; then
    dirsquare=/home/"$cuser"/.icons/Numix-Square/
elif [ -d /usr/share/icons/Numix-Square/ ]; then
     dirsquare=/usr/share/icons/Numix-Square/
else
    square=false
fi

base=true
if [ -d /home/"$cuser"/.local/share/icons/Numix/ ]; then
    dirbase=/home/"$cuser"/.local/share/icons/Numix
elif [ -d /home/"$cuser"/.icons/Numix/ ]; then
    dirbase=/home/"$cuser"/.icons/Numix/
elif [ -d /usr/share/icons/Numix/ ]; then
     dirbase=/usr/share/icons/Numix/
else
    base=false
fi

if $circle; then 
    cd $dircircle"48/apps" || exit
    ln -sf calendar-blue-"$day".svg google-calendar.svg
    ln -sf calendar-purple-"$day".svg ms-calendar.svg
    ln -sf calendar-red-"$day".svg office-calendar.svg
    gtk-update-icon-cache --force $dircircle
fi

if $square; then 
    cd $dirsquare"48/apps" || exit
    ln -sf calendar-blue-"$day".svg google-calendar.svg
    ln -sf calendar-purple-"$day".svg ms-calendar.svg
    ln -sf calendar-red-"$day".svg office-calendar.svg
    gtk-update-icon-cache --force $dirsquare
fi

if $base; then 
    cd $dirbase || exit
    places=$(find . -name "places" -type d)
    for place in $places
        do
            cd "$dirbase$place" || exit
            ln -sf calendar-"$day".svg calendar.svg
        done
    gtk-update-icon-cache --force $dirbase
fi
